[phases.setup]
nixPkgs = ["libxcb", "libGL", "glib"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip uninstall -y opencv-python opencv-contrib-python || true",
  "pip install -r requirements.txt"
]